name: GITHUB_OUTPUT
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source                                  # ステップIDを指定
        run: echo "result=Hello" >> "${GITHUB_ENV}" # GITHUB_OUTPUTへ書き出し
      - env:
          RESULT: ${{ steps.source.outputs.result }}  # GITHUB_OUTPUTから読み込み
        run: echo "Result: $RESULT"                 # 結果を表示