name: Manual
on:
 workflow_dispatch:                   # 手動実行イベント
  inputs:
    greeting:                         # 入力パラメータ名
      type: string                    # データ型
      degault: Hello
      required: true                  # 必須フラグ
      description: A cheerful world   # 説明文
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.greeting }} # 入力パラメータの参照